[package]
name = "rust-apple2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-6502 = { git = "https://github.com/kurtjd/rust-6502.git", branch = "main" }
